server:
  port: 8081
  servlet:
    context-path: /bolo

spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/soup
   username: root
   password: root
 jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8